-- Invitations: one-time signup links that pre-assign a new client to staff.
create table if not exists invitations (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  full_name text not null default '',
  role text not null default 'client' check (role in ('client')),
  consultant_id uuid references profiles(id) on delete set null,
  psychologist_id uuid references profiles(id) on delete set null,
  created_by uuid references profiles(id) on delete set null,
  used_at timestamptz,
  used_by uuid references profiles(id) on delete set null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_invitations_token on invitations(token);
create index if not exists idx_invitations_created_by on invitations(created_by);

-- Audit log: record administrative actions for accountability.
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_log_created_at on audit_log(created_at desc);
