alter table decisions
  add column if not exists finalized_at timestamptz,
  add column if not exists latest_outcome_event_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'decisions_status_check'
      and conrelid = 'decisions'::regclass
  ) then
    alter table decisions
      add constraint decisions_status_check
      check (status in ('pending', 'success', 'fail'));
  end if;
end $$;

create table if not exists decision_outcome_events (
  id bigint generated by default as identity primary key,
  decision_id bigint not null references decisions(id) on delete cascade,
  actor_user_id uuid not null references profiles(id) on delete cascade,
  event_type text not null check (event_type in ('finalized', 'reopened', 'revised')),
  from_status text not null check (from_status in ('pending', 'success', 'fail')),
  to_status text not null check (to_status in ('pending', 'success', 'fail')),
  outcome_reason text not null default '',
  reflection_payload jsonb,
  created_at timestamptz not null default now(),
  revision_of_event_id bigint references decision_outcome_events(id) on delete set null
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'decisions_latest_outcome_event_id_fkey'
      and conrelid = 'decisions'::regclass
  ) then
    alter table decisions
      add constraint decisions_latest_outcome_event_id_fkey
      foreign key (latest_outcome_event_id)
      references decision_outcome_events(id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_decisions_status on decisions(status);
create index if not exists idx_decisions_finalized_at on decisions(finalized_at);
create index if not exists idx_outcome_events_decision_created_at on decision_outcome_events(decision_id, created_at desc);
create index if not exists idx_outcome_events_actor_created_at on decision_outcome_events(actor_user_id, created_at desc);
create index if not exists idx_outcome_events_finalized_transitions
  on decision_outcome_events(decision_id, created_at desc)
  where to_status in ('success', 'fail');
