-- Comments schema aligned with bigint decision/task/item IDs
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  decision_id bigint references public.decisions(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  target_item_id bigint references public.decision_items(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  section text default 'general',
  visibility text check (visibility in ('public', 'internal')) default 'public',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;

drop policy if exists "Users can view comments based on role and visibility" on public.comments;
drop policy if exists "Clients can view public comments for their own decisions" on public.comments;
drop policy if exists "Clients can create comments on their own decisions" on public.comments;
drop policy if exists "Staff can comment" on public.comments;

create policy "Users can view comments based on decision access and visibility"
on public.comments for select
to authenticated
using (
  exists (
    select 1 from public.decisions
    where public.decisions.id = public.comments.decision_id
    and (
      public.decisions.user_id = auth.uid()
      or exists (
        select 1 from public.profiles owner_profile
        where owner_profile.id = public.decisions.user_id
        and owner_profile.consultant_id = auth.uid()
      )
      or exists (
        select 1 from public.profiles current_profile
        where current_profile.id = auth.uid()
        and current_profile.role in ('psychologist', 'supervisor')
      )
    )
  )
  and not (
    public.comments.visibility = 'internal'
    and exists (
      select 1 from public.decisions
      where public.decisions.id = public.comments.decision_id
      and public.decisions.user_id = auth.uid()
    )
  )
);

create policy "Users can insert comments based on decision access"
on public.comments for insert
to authenticated
with check (
  public.comments.user_id = auth.uid()
  and (
    exists (
      select 1 from public.decisions
      where public.decisions.id = public.comments.decision_id
      and public.decisions.user_id = auth.uid()
      and public.comments.visibility = 'public'
    )
    or exists (
      select 1 from public.decisions
      join public.profiles owner_profile on owner_profile.id = public.decisions.user_id
      where public.decisions.id = public.comments.decision_id
      and owner_profile.consultant_id = auth.uid()
    )
    or exists (
      select 1 from public.profiles current_profile
      where current_profile.id = auth.uid()
      and current_profile.role in ('psychologist', 'supervisor')
    )
  )
);
