create extension if not exists pgcrypto;

create table if not exists profiles (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  username text not null unique,
  password_hash text not null,
  full_name text not null,
  role text not null default 'client' check (role in ('client', 'consultant', 'supervisor', 'psychologist')),
  consultant_id uuid references profiles(id)
);

create table if not exists decisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  title text not null default '',
  description text not null default '',
  step int not null default 1,
  status text not null default 'pending' check (status in ('pending', 'success', 'fail')),
  outcome_reason text not null default '',
  finalized_at timestamptz,
  latest_outcome_event_id bigint
);

create table if not exists decision_outcome_events (
  id bigint generated by default as identity primary key,
  decision_id bigint not null references decisions(id) on delete cascade,
  actor_user_id uuid not null references profiles(id) on delete cascade,
  event_type text not null check (event_type in ('finalized', 'reopened', 'revised')),
  from_status text not null check (from_status in ('pending', 'success', 'fail')),
  to_status text not null check (to_status in ('pending', 'success', 'fail')),
  outcome_reason text not null default '',
  reflection_payload jsonb,
  created_at timestamptz not null default now(),
  revision_of_event_id bigint references decision_outcome_events(id) on delete set null
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'decisions_latest_outcome_event_id_fkey'
  ) then
    alter table decisions
      add constraint decisions_latest_outcome_event_id_fkey
      foreign key (latest_outcome_event_id)
      references decision_outcome_events(id)
      on delete set null;
  end if;
end $$;

create table if not exists decision_items (
  id bigint generated by default as identity primary key,
  decision_id bigint not null references decisions(id) on delete cascade,
  created_at timestamptz not null default now(),
  type text not null check (type in ('pro', 'con')),
  text text not null,
  weight int not null default 0,
  strategy text not null default ''
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  decision_item_id bigint not null references decision_items(id) on delete cascade,
  created_at timestamptz not null default now(),
  content text not null,
  is_completed boolean not null default false
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  decision_id bigint not null references decisions(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  content text not null,
  target_item_id bigint references decision_items(id) on delete cascade,
  task_id bigint references tasks(id) on delete cascade,
  section text not null default 'general',
  visibility text not null default 'public' check (visibility in ('public', 'internal')),
  created_at timestamptz not null default now()
);

create index if not exists idx_profiles_consultant_id on profiles(consultant_id);
create index if not exists idx_decisions_user_id on decisions(user_id);
create index if not exists idx_decisions_status on decisions(status);
create index if not exists idx_decisions_finalized_at on decisions(finalized_at);
create index if not exists idx_decision_items_decision_id on decision_items(decision_id);
create index if not exists idx_tasks_decision_item_id on tasks(decision_item_id);
create index if not exists idx_comments_decision_id on comments(decision_id);
create index if not exists idx_comments_task_id on comments(task_id);
create index if not exists idx_outcome_events_decision_created_at on decision_outcome_events(decision_id, created_at desc);
create index if not exists idx_outcome_events_actor_created_at on decision_outcome_events(actor_user_id, created_at desc);
create index if not exists idx_outcome_events_finalized_transitions
  on decision_outcome_events(decision_id, created_at desc)
  where to_status in ('success', 'fail');
