-- Reset Schema (Drop existing tables to ensure clean state)
drop table if exists decision_items;
drop table if exists decisions;
drop table if exists profiles;

-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  role text check (role in ('client', 'consultant', 'supervisor', 'psychologist')) default 'client',
  consultant_id uuid references profiles(id)
);

-- Set up RLS for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for decisions
create table decisions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  description text,
  step int default 1,
  status text default 'pending',
  outcome_reason text
);

-- Set up RLS for decisions
alter table decisions enable row level security;

create policy "Individuals can view their own decisions."
  on decisions for select
  using (
    auth.uid() = user_id
    or exists (
      select 1 from profiles
      where profiles.id = decisions.user_id
      and profiles.consultant_id = auth.uid()
    )
  );

create policy "Individuals can create their own decisions."
  on decisions for insert
  with check ( auth.uid() = user_id );

create policy "Individuals can update their own decisions."
  on decisions for update
  using ( auth.uid() = user_id );

create policy "Individuals can delete their own decisions."
  on decisions for delete
  using ( auth.uid() = user_id );

-- Create a table for decision items (Pros and Cons)
create table decision_items (
  id bigint generated by default as identity primary key,
  decision_id bigint references decisions(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text check (type in ('pro', 'con')) not null,
  text text not null,
  weight int default 0,
  strategy text
);

-- Set up RLS for decision_items
alter table decision_items enable row level security;

create policy "Users can view items of their decisions"
  on decision_items for select
  using (
    exists (
      select 1 from decisions
      where decisions.id = decision_items.decision_id
      and (
        decisions.user_id = auth.uid()
        or exists (
          select 1 from profiles
          where profiles.id = decisions.user_id
          and profiles.consultant_id = auth.uid()
        )
      )
    )
  );

create policy "Users can insert items to their decisions"
  on decision_items for insert
  with check (
    exists (
      select 1 from decisions
      where decisions.id = decision_items.decision_id
      and decisions.user_id = auth.uid()
    )
  );

create policy "Users can update items of their decisions"
  on decision_items for update
  using (
    exists (
      select 1 from decisions
      where decisions.id = decision_items.decision_id
      and decisions.user_id = auth.uid()
    )
  );

create policy "Users can delete items of their decisions"
  on decision_items for delete
  using (
    exists (
      select 1 from decisions
      where decisions.id = decision_items.decision_id
      and decisions.user_id = auth.uid()
    )
  );

-- Create tasks table
create table tasks (
  id bigint generated by default as identity primary key,
  decision_item_id bigint references decision_items(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  is_completed boolean default false
);

-- Set up RLS for tasks
alter table tasks enable row level security;

create policy "Users can view tasks of their decision items"
  on tasks for select
  using (
    exists (
      select 1 from decision_items
      join decisions on decisions.id = decision_items.decision_id
      where decision_items.id = tasks.decision_item_id
      and (
        decisions.user_id = auth.uid()
        or exists (
          select 1 from profiles
          where profiles.id = decisions.user_id
          and profiles.consultant_id = auth.uid()
        )
      )
    )
  );

create policy "Users can insert tasks to their decision items"
  on tasks for insert
  with check (
    exists (
      select 1 from decision_items
      join decisions on decisions.id = decision_items.decision_id
      where decision_items.id = tasks.decision_item_id
      and decisions.user_id = auth.uid()
    )
  );

create policy "Users can update tasks of their decision items"
  on tasks for update
  using (
    exists (
      select 1 from decision_items
      join decisions on decisions.id = decision_items.decision_id
      where decision_items.id = tasks.decision_item_id
      and decisions.user_id = auth.uid()
    )
  );

create policy "Users can delete tasks of their decision items"
  on tasks for delete
  using (
    exists (
      select 1 from decision_items
      join decisions on decisions.id = decision_items.decision_id
      where decision_items.id = tasks.decision_item_id
      and decisions.user_id = auth.uid()
    )
  );

