-- Unified Schema Update Script
-- This script creates the 'tasks' and 'comments' tables with the correct data types (BigInt) to match your existing 'decisions' and 'decision_items' tables.

-- 1. Create 'tasks' table
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  decision_item_id bigint references public.decision_items(id) on delete cascade not null,
  content text not null,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.tasks enable row level security;

-- Policies for tasks
create policy "Clients can manage their own tasks"
on public.tasks
for all
to authenticated
using (
  decision_item_id in (
    select id from public.decision_items where decision_id in (
      select id from public.decisions where user_id = auth.uid()
    )
  )
)
with check (
  decision_item_id in (
    select id from public.decision_items where decision_id in (
      select id from public.decisions where user_id = auth.uid()
    )
  )
);

create policy "Staff can view tasks"
on public.tasks for select
to authenticated
using ( true );


-- 2. Create 'comments' table (fixing types to use BigInt for foreign keys to decisions/items)
create table if not exists public.comments (
  id uuid primary key default uuid_generate_v4(), -- We can keep ID as UUID or BigInt. UUID is fine for comments.
  decision_id bigint references public.decisions(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  target_item_id bigint references public.decision_items(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  section text default 'general',
  visibility text default 'public',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.comments enable row level security;

-- Policies for comments

-- Select Policy
create policy "Users can view comments based on role and visibility"
on public.comments for select
to authenticated
using (
  user_id = auth.uid()
  OR
  (
    decision_id in (select id from public.decisions where user_id = auth.uid())
    and visibility = 'public'
  )
  OR
  (
    -- Staff access: can see all comments unless it's their own "Client" account scope (prevented by above rules mostly)
    -- Simplified: If you are NOT the owner of the decision, and you have access to the decision, you see everything?
    -- Actually, for 'internal' comments, the Client (owner) must NOT see them.
    -- The logic below ensures that if you are the client (owner), you only see 'public'.
    -- If you are NOT the client, you see everything.
    exists (
       select 1 from public.decisions d
       where d.id = comments.decision_id
       and d.user_id != auth.uid() -- You are not the owner
    )
  )
);

-- Insert Policy
create policy "Users can insert comments"
on public.comments for insert
to authenticated
with check (
  -- Allow if you are the owner (Client) OR if you are Staff (not owner)
  -- Simplified check for now: If you can view the decision, you can comment.
  exists (
    select 1 from public.decisions d
    where d.id = decision_id
    and (d.user_id = auth.uid() or true) -- Staff check usually handled by profile role but RLS access to decision is enough proxy
  )
);

-- Note: Tables created with 'if not exists' will not fail if they exist.
-- However, if 'comments' already exists with WRONG types (UUID), this script might not fix it automatically without dropping.
-- If you run into errors about existing columns, please RUN: drop table public.comments; AND drop table public.tasks; first.
