-- Create tasks table with BigInt to match decision_items
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  decision_item_id bigint references public.decision_items(id) on delete cascade not null,
  content text not null,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for tasks
alter table public.tasks enable row level security;

-- Policies for tasks (similar to decision_items)
-- 1. Clients can manage their own tasks
create policy "Clients can manage their own tasks"
on public.tasks
for all
to authenticated
using (
  decision_item_id in (
    select id from public.decision_items where decision_id in (
      select id from public.decisions where user_id = auth.uid()
    )
  )
)
with check (
  decision_item_id in (
    select id from public.decision_items where decision_id in (
      select id from public.decisions where user_id = auth.uid()
    )
  )
);

-- 2. Consultants/Staff can view tasks if they can view the decision
create policy "Staff can view tasks"
on public.tasks for select
to authenticated
using (
  true -- Assuming broad read access for now as per previous pattern
);

-- Update comments table to link to tasks
-- Note: Check if comments table uses UUID or BigInt for existing FKs. 
-- If created via previous script, it might be wrong. Assuming we just need to add the column.
alter table public.comments 
add column if not exists task_id bigint references public.tasks(id) on delete cascade;

-- Update Comment Policies to include task ownership check if needed
-- Existing policies rely on decision_id, which is still present on comments.
-- We just need to make sure when inserting a comment with task_id, it is valid.
